#!/usr/bin/env bash
# ===========================================================================
# setup_git_hooks.sh — Set up pre-commit hooks for a data engineering project
# ===========================================================================
# This script:
#   1. Checks that Python is installed
#   2. Installs pre-commit if not present
#   3. Copies .pre-commit-config.yaml from templates/ if not present
#   4. Runs pre-commit install
#   5. Runs pre-commit run --all-files to verify
#   6. Installs nbstripout for Jupyter notebooks
#   7. Configures git for conventional commit messages (optional)
#   8. Prints a success message with next steps
#
# Usage:
#   chmod +x scripts/setup_git_hooks.sh
#   ./scripts/setup_git_hooks.sh
# ===========================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Globals
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATES_DIR="$PROJECT_ROOT/templates"
PRECOMMIT_CONFIG="$PROJECT_ROOT/.pre-commit-config.yaml"
TEMPLATE_CONFIG="$TEMPLATES_DIR/.pre-commit-config.yaml"

# Colours (disabled if not a TTY)
if [ -t 1 ]; then
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    RED='\033[0;31m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    GREEN='' YELLOW='' RED='' BLUE='' NC=''
fi

log_info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }
log_step()  { echo -e "\n${BLUE}=== $* ===${NC}"; }

# ---------------------------------------------------------------------------
# 1. Check Python is installed
# ---------------------------------------------------------------------------
log_step "Checking Python installation"

if ! command -v python3 &>/dev/null && ! command -v python &>/dev/null; then
    log_error "Python is not installed or not on PATH."
    log_error "Install Python 3.8+ from https://www.python.org/downloads/ and re-run this script."
    exit 1
fi

# Use python3 if available, fall back to python
PYTHON_CMD="python3"
if ! command -v python3 &>/dev/null; then
    PYTHON_CMD="python"
fi

PYTHON_VERSION="$($PYTHON_CMD --version 2>&1)"
log_info "Found: $PYTHON_VERSION ($PYTHON_CMD)"

# ---------------------------------------------------------------------------
# 2. Install pre-commit if not present
# ---------------------------------------------------------------------------
log_step "Checking pre-commit"

if command -v pre-commit &>/dev/null; then
    log_info "pre-commit is already installed: $(pre-commit --version)"
else
    log_info "Installing pre-commit via pip..."
    $PYTHON_CMD -m pip install --user pre-commit
    # Ensure user bin is on PATH
    USER_BIN="$($PYTHON_CMD -m site --user-base)/bin"
    if [ -d "$USER_BIN" ] && [[ ":$PATH:" != *":$USER_BIN:"* ]]; then
        export PATH="$USER_BIN:$PATH"
        log_warn "Added $USER_BIN to PATH for this session."
        log_warn "Add 'export PATH=\"$USER_BIN:\$PATH\"' to your shell profile for persistence."
    fi
    if ! command -v pre-commit &>/dev/null; then
        log_error "pre-commit installation failed."
        exit 1
    fi
    log_info "pre-commit installed: $(pre-commit --version)"
fi

# ---------------------------------------------------------------------------
# 3. Copy .pre-commit-config.yaml from templates/ if not present
# ---------------------------------------------------------------------------
log_step "Setting up .pre-commit-config.yaml"

if [ -f "$PRECOMMIT_CONFIG" ]; then
    log_info ".pre-commit-config.yaml already exists at project root."
else
    if [ -f "$TEMPLATE_CONFIG" ]; then
        cp "$TEMPLATE_CONFIG" "$PRECOMMIT_CONFIG"
        log_info "Copied .pre-commit-config.yaml from templates/ to project root."
    else
        log_warn "No template found at $TEMPLATE_CONFIG"
        log_warn "Creating a minimal .pre-commit-config.yaml..."

        cat > "$PRECOMMIT_CONFIG" << 'FALLBACK'
# Minimal pre-commit configuration (auto-generated by setup_git_hooks.sh)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--extend-ignore=E203,W503"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
FALLBACK
        log_info "Created minimal .pre-commit-config.yaml at project root."
    fi
fi

# ---------------------------------------------------------------------------
# 4. Run pre-commit install
# ---------------------------------------------------------------------------
log_step "Installing pre-commit git hooks"

if [ ! -d "$PROJECT_ROOT/.git" ]; then
    log_warn "No .git directory found in $PROJECT_ROOT — initialising git repository..."
    git -C "$PROJECT_ROOT" init
fi

cd "$PROJECT_ROOT"
pre-commit install
pre-commit install --hook-type commit-msg
log_info "pre-commit hooks installed."

# ---------------------------------------------------------------------------
# 5. Run pre-commit run --all-files to verify
# ---------------------------------------------------------------------------
log_step "Running pre-commit on all files (verification)"

if pre-commit run --all-files; then
    log_info "All pre-commit checks passed."
else
    EXIT_CODE=$?
    log_warn "pre-commit found issues (exit code: $EXIT_CODE)."
    log_warn "Run 'pre-commit run --all-files' again after fixing the issues."
    # Don't fail the script — the hooks are installed and ready to use.
fi

# ---------------------------------------------------------------------------
# 6. Install nbstripout for Jupyter notebooks
# ---------------------------------------------------------------------------
log_step "Setting up nbstripout for Jupyter notebooks"

if ! $PYTHON_CMD -c "import nbstripout" 2>/dev/null; then
    log_info "Installing nbstripout..."
    $PYTHON_CMD -m pip install --user nbstripout
else
    log_info "nbstripout is already installed."
fi

if command -v nbstripout &>/dev/null; then
    nbstripout --install
    log_info "nbstripout installed as a git filter (cleans notebooks on commit)."
else
    USER_BIN="$($PYTHON_CMD -m site --user-base)/bin"
    if [ -f "$USER_BIN/nbstripout" ]; then
        export PATH="$USER_BIN:$PATH"
        nbstripout --install
        log_info "nbstripout installed as a git filter."
    else
        log_warn "nbstripout binary not found on PATH. Install manually: pip install nbstripout && nbstripout --install"
    fi
fi

# ---------------------------------------------------------------------------
# 7. Configure git for conventional commit messages (optional)
# ---------------------------------------------------------------------------
log_step "Configuring conventional commit message template (optional)"

COMMIT_MSG_TEMPLATE="$PROJECT_ROOT/.git-message-template"

cat > "$COMMIT_MSG_TEMPLATE" << 'COMMIT_TEMPLATE'
# Conventional Commits format:
#   <type>(<scope>): <subject>
#
#   <body>
#
#   <footer>
#
# Types:
#   feat     A new feature
#   fix      A bug fix
#   docs     Documentation only changes
#   style    Changes that do not affect the meaning of the code (formatting, etc)
#   refactor A code change that neither fixes a bug nor adds a feature
#   perf     A code change that improves performance
#   test     Adding missing or correcting existing tests
#   chore    Changes to the build process or auxiliary tools
#   ci       Changes to CI configuration files and scripts
#   revert   Revert a previous commit
#
# Example:
#   feat(pipeline): add incremental load for sales事实表
#
#   - Added watermark column tracking
#   - Configured MERGE operation for upserts
#
#   Closes #142
COMMIT_TEMPLATE

# Set the template (non-fatal if it fails)
if git config commit.template "$COMMIT_MSG_TEMPLATE" 2>/dev/null; then
    log_info "Git commit message template configured: $COMMIT_MSG_TEMPLATE"
else
    log_warn "Could not set git commit template. You can set it manually:"
    log_warn "  git config commit.template $COMMIT_MSG_TEMPLATE"
fi

# ---------------------------------------------------------------------------
# 8. Print success message with next steps
# ---------------------------------------------------------------------------
log_step "Setup Complete!"

echo -e "
${GREEN}╔════════════════════════════════════════════════════════════╗${NC}
${GREEN}║          Git Hooks Setup — Success!                        ║${NC}
${GREEN}╚════════════════════════════════════════════════════════════╝${NC}

${BLUE}What was configured:${NC}
  ${GREEN}✓${NC} Python verified ($PYTHON_VERSION)
  ${GREEN}✓${NC} pre-commit installed and hooks registered
  ${GREEN}✓${NC} .pre-commit-config.yaml ready at project root
  ${GREEN}✓${NC} nbstripout configured for Jupyter notebooks
  ${GREEN}✓${NC} Conventional commit message template set

${BLUE}Next Steps:${NC}
  1. Review and customise ${YELLOW}.pre-commit-config.yaml${NC} for your project.
  2. Stage your files:  ${YELLOW}git add -A${NC}
  3. Commit:            ${YELLOW}git commit${NC}  (hooks run automatically)
  4. To run hooks manually on all files:
     ${YELLOW}pre-commit run --all-files${NC}
  5. To update hook versions:
     ${YELLOW}pre-commit autoupdate${NC}

${BLUE}Useful Commands:${NC}
  ${YELLOW}pre-commit clean${NC}              — Clear the pre-commit cache
  ${YELLOW}pre-commit run <hook-id>${NC}      — Run a specific hook
  ${YELLOW}nbstripout --status${NC}           — Check nbstripout status
  ${YELLOW}git config --list | grep template${NC}  — Verify commit template

${BLUE}Happy coding! 🚀${NC}
"

exit 0
